### ISSUE TITLE
Inconsistent password pasting behavior

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [Canop/safecloset#15]
I don't know if this trivial behavior is caused by safecloset or the terminal. It behaves exactly the same on Windows Terminal, cmd.exe and the native PowerShell console. It behaves like this.

https://user-images.githubusercontent.com/39968/142635139-3f0c2caf-c28f-4b18-aec3-e7cf5dc574c0.mp4

Not a big issue, just curious why it behaves like this.

**Comment by Canop** [comment]
TBH I didn't consider anybody would ever want to have the password of a drawer in the clipboard. I mean... this is very unsecure...

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> TBH I didn't consider anybody would ever want to have the password of a drawer in the clipboard. I mean... this is very unsecure...

Yes, I totally agree. In my case, I'm pasting a very long "password base" text. After that, I have to manually edit it in multiple positions in a complex way to make it the the correct working one. This way, even people got my copied password base text, they can't use it in any way. I just have to ensure there is no keylogger. I do this, because the real password is too long and it's not possible to remember and type them.

**Comment by Canop** [comment]
I think it's important to be able to keep the passphrase in head. This lets you have just the binary and closet files at several not protected locations, even online, so that you can fetch your secrets where you don't expect to be. There are IMO ways to devise passphrases which aren't brute-forcable and can still be kept in mind, even if unused for years.

An example would be to start from a sentence which makes sense only for you, it may come from your childhood or whatever. Then you add two or three typos or random (easy to type) characters at places you're sure to remember. Even playing with case is enough to increase entropy a lot.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
I know this trick but I never tried. Thanks for the suggestion and I'll definitely get my hands dirty and give it a try.
