### ISSUE TITLE
Backslash character can't be displayed properly

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [Canop/safecloset#22]
![char_issue](https://user-images.githubusercontent.com/39968/190629191-2858a5af-8dc0-4ff5-a2cf-68ef9a99180b.gif)

I'm on Windows. Not sure if this issue exists on other platforms.

**Comment by Canop** [comment]
I confirm the problem, it's not specific to Windows.

**Comment by Canop** [comment]
This is due to the text being considered as markdown and the parser not being discriminant enough regarding the characters which can be escaped.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Interesting. Do you mean SafeCloset actually parse the content in it as markdown? Good to know that. But I mainly store secrets in SafeCloset, which I suppose this tool is designed for. Most secrets are not in markdown format. If this is a note taking tool, markdown is more suitable. Do you think adding an option to disable markdown parsing a good idea? Or disable it by default and only enable it when some parameter is passed to SafeCloset? I don't know, just some options.

**Comment by Canop** [comment]
Options are painful to manage, and it's harder to make sense of behaviors when they change according to local options.

The reason I added markdown support for values is because structured notes are easier to read this way, and safecloset isn't just for passwords.

Now, I agree that markdown rendering is rarely useful in practice in safecloset, I'm not sure it was really a good idea.

I'll start by fixing it, and, afterwards, keeping markdown for values will be another question.

**Comment by Canop** [comment]
Fixed in v0.6.4
