### ISSUE TITLE
Does anybody need an "import" function ?

### ISSUE THREAD

**Issue by Canop** [Canop/safecloset#24]
From the very start I considered that at some point I'd need a feature allowing you to import entries from a drawer to another one, either within the same file or from a different file.

Two use-cases:
- merging changes made in different places
- merge two drawers because you realize you don't need to be so paranoid

It turns out that I never felt the need so I didn't code this until now.

But the plan is ready, so, please, if you'd like this function, tell me.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
This is a useful feature. Does your plan include deep drawers inside other top-level drawers? If we have this feature, basically we can move drawer around, which is a cool feature.

**Comment by Canop** [comment]
You would be able to import any drawer's content (selecting what you want to take) from any drawer, yes.

**Comment by paletochen** [comment]
I'd love this feature.
It also allows to fix some other collateral problems.
For example: I created by mistake a deep drawer, instead of an open one, in an already big file with 3 other drawers, and i cannot delete it as there is no such function.
Moving drawers around it would allow me to move my existing drawers to another file which i can keep a bit more clean

(I know an extra drawer doesn't hurt but it drives me a bit nuts knowing that it is there ;) )

**Comment by Canop** [comment]
Hum. Deleting a drawer would be another feature. There's no reason not to have it.

**Comment by Canop** [comment]
BTW I'm on the import feature, it's almost complete.

**Comment by paletochen** [comment]
Would this import work only between drawers.. or would it also allow import external content, like through an csv file, or something like that?
I can imagine easily importing all my passwords, for example, from Google Chrome by just providing a csv file with 2 columns

**Comment by Canop** [comment]
I only considered importing from drawers but importing from a csv file would be very easy so I'll do it too.

**Comment by Canop** [comment]
Importing from another drawer can be tested now: https://github.com/Canop/safecloset/pull/26
