### ISSUE TITLE
Question: drop markdown rendering of values ?

### ISSUE THREAD

**Issue by Canop** [Canop/safecloset#28]
Right now, values are rendered as markdown when not edited.

It turns out there are really few cases it makes sense.

Do I
- just completely remove markdown rendering ?
- make it opt-in with new settings at the drawer level ?

**Comment by paletochen** [comment]
I've never thought of using markdown in the values, as I have been using safecloset as a traditional password manager, but now that I know that this feature exists, it may open some other possibilities for me.

Having said that, I believe that most of the people may use safecloset like me, like a password manager, or standard key,value storage system. So this means that I think the default behavior should be to not render the values as markdown to avoid confusions, as I experienced in https://github.com/Canop/safecloset/issues/27

I would then vote for having the markdown feature disabled by default and make it an opt-in feature through the settings.

I believe that someone looking for such a feature may eventually investigate and find that option in the menu

**Comment by Canop** [comment]
Done in https://github.com/Canop/safecloset/pull/29

**Comment by nikolasumus** [comment]
> I've never thought of using markdown in the values, as I have been using safecloset as a traditional password manager, but now that I know that this feature exists, it may open some other possibilities for me.

If U using it as a traditional password manager, maybe, U can explain, how U do this?) Because for me it is uncomfortable to have no ability to store logins and passwords in one entry but have ability to copy them separately in fast and easy way. Maybe, it is possible, but I just not figured out, how. Or U just make separate entries, like "google-login <value>; google-pass <value>"?
