### ISSUE TITLE
[bug?] Can't copy on MacOS

### ISSUE THREAD

**Issue by jclmnop** [Canop/safecloset#30]
MacOS: 13.2.1 (Ventura)
Arch: arm64 (M1)

I can't seem to copy any secrets to the clipboard. I've tried it with the standard terminal app, so it's not my terminal app (Warp) causing the issue as far as I can tell. 

When I use `^c`, the notification at the bottom shows up saying it's been copied to the clipboard, but it hasn't actually been copied to system clipboard. I can't copy with cmd+c either. Doesn't matter whether I select a string or try to copy the whole entry. 

Weird thing is I can still paste into an entry from the system clipboard with cmd+v, but I can't copy to the clipboard at all.

**Comment by Canop** [comment]
Making copy-paste work is always hard, especially on Mac for me as I don't have a Mac and can't directly test.

There's a new version of the [terminal-clipboard](https://docs.rs/terminal-clipboard/latest/terminal_clipboard/) crate, it's supposed to improve copy-pasting on Mac. I didn't include it in safecloset yet because of this "testing on mac" problem.

Could you try modify safecloset's Cargo.lock file and see whether it works better with `terminal-clipboard = "0.4"` ?

If I'm not clear, please come to the chat: https://miaou.dystroy.org/3768

**Comment by jclmnop** [comment]
Changed `teminal-clipboard` to `"0.4.0"` in Cargo.toml, reinstalled it using my modified local version, and I can now copy and paste without any issues. 

Thanks man 👍

**Comment by Canop** [comment]
(reopening until I release a new version of SafeCloset)

**Comment by Canop** [comment]
version 1.2.2 of safecloset released
